### ISSUE TITLE
Add more keys to the keylist

### ISSUE THREAD

**Issue by sethherr** [ErgoDox-EZ/docs#3]
Add information from [jackhumbert/qmk_firmware](https://github.com/jackhumbert/qmk_firmware) about custom modifier keys.

This seems like a good place to document what keys are available. We could pull this list of keys and put it into fusion.

Or we could put this keylist directly into fusion. Unclear where the best place for it is.

**Comment by ezuk** [comment]
That's one of the reasons I said I feel the firmware subdirectory in the repo is the right place for the docs; otherwise we get duplication, and it's not DRY so if things change we have multiple places to change. 

I suggest not including anything here that's included in the qmk repo docs. We can link there - "for a list of keycodes, click here".

For Fusion, there's eventually going to be on-screen docs, I discussed this with @tdegrunt at the time.

**Comment by sethherr** [comment]
Fair. I was trying to get the docs started for Fusion. I'll move this over to fusion and start displaying them there.

I'm very excited to have the additional keys and options unavailable from the massdrop configurator, and I refuse to write the c file manually ;)
