### ISSUE TITLE
"Check out the list of keys and their names in c" link is not working.

### ISSUE THREAD

**Issue by ghost** [ErgoDox-EZ/docs#6]
In the README.markdown https://github.com/ErgoDox-EZ/docs/blob/master/keylist.tsv is no longer working.

**Comment by ghost** [comment]
Was this gist the intended target? https://gist.github.com/sethherr/5991b0d79a5c93b46a1f

**Comment by ezuk** [comment]
This is where I'd point it: https://github.com/jackhumbert/qmk_firmware/blob/master/tmk_core/doc/keycode.txt

@sethherr - I am getting the feeling this repo isn't getting enough love for it to be the official docs repo. I'm considering merging things into qmk somehow and maybe doing away with this one, as it seems to be confusing people. Thoughts?

**Comment by sethherr** [comment]
Well, I switched the link back to the correct keylist.

I made my opinions clear when creating this about why I thought there should be a separate docs page, actually under the ErgoDox EZ name instead of having it under the qmk firmware repository. The very fact that people are actually looking at this at all, despite that it isn't really linked from anywhere suggests that it has some utility.
